[package]
name = "mocketd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
clap = "4.5.16"
lazy_static = "1.5.0"
serde_json = "1.0.125"
tokio = { version = "1", features = ["full"] }
wasmtime = "23.0.2"
